### ISSUE TITLE
running into issues while creating the docker image

### ISSUE THREAD

**Issue by amithpatrick1** [ibm-datapower/datapower-labs#2]
Hi Team,

I am getting the below error while creating the docker file:

Loaded plugins: ovl, product-id, search-disabled-repos, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
There are no enabled repos.
 Run "yum repolist all" to see the repos you have.
 You can enable repos with yum-config-manager --enable <repo>

**Comment by hstenzel** [comment]
Hello,

It sounds like a setup issue with your RHEL host. Follow RedHat's instructions for "Gettind Docker in RHEL 7, available here:

https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/version-7/getting-started-with-containers/#getting_docker_in_rhel_7

There are 6 steps, and it covers adding the subscription manager.

Let me know if this helps.

**Comment by hstenzel** [comment]
Closing; this is really a question for RedHat. If there's other info that would be helpful, I'd definitely like to collect it though.
