### ISSUE TITLE
Docker image won't start

### ISSUE THREAD

**Issue by tsikorski** [ibm-datapower/datapower-labs#3]
Hi,
I am running docker-engine 1.11.1 and trying to get datapower to run in a docker container. I downloaded the .deb files from passport  and tried using the Dockerfile from the quickstart and this git repository. The build succeeded however when I issued the following run command 

docker run -it  -h datapower --privileged   datapower /bin/bash
I then issue the  

/opt/ibm/datapower/datapower-launch

and get the following results. Running non interactively with the -d option and looking at the logs after leads to the same error messages.

Thu Apr 28 2016 10:50:09 ERR dpControl [pre-start][20] Cannot run losetup --show --find /var/opt/ibm/datapower/datapower.img
Thu Apr 28 2016 10:50:09 ERR dpControl [pre-start][20]    losetup: losetup: Could not find any loop device. Maybe this kernel does not know
Thu Apr 28 2016 10:50:09 ERR dpControl [pre-start][20]    losetup:        about the loop device? (If so, recompile or `modprobe loop'.)
Thu Apr 28 2016 10:50:09 ERR dpControl [post-stop][20] Cannot open lockfile '/var/opt/ibm/datapower/datapower.img.lck': No such file or directory
Thu Apr 28 2016 10:50:09 ERR dpControl [post-stop][20] Cannot close LUKS partition 'var_opt_ibm_datapower_datapower_img': No such device (error 19)
Thu Apr 28 2016 10:50:09 ERR dpControl [post-stop][20] Cannot open lockfile '/var/opt/ibm/datapower/datapower.img.lck': No such file or directory
Thu Apr 28 2016 10:50:10 ERR dpControl [post-stop][20] Cannot open lockfile '/var/opt/ibm/datapower/datapower.img.lck': No such file or directory
Thu Apr 28 2016 10:50:10 ERR dpControl [post-stop][20] Cannot open lockfile '/var/opt/ibm/datapower/datapower.img.lck': No such file or directory

Any idea what is going on? Should I open a pmr?

Here are the relevant parts of the build process:

Setting up telnet (0.17-36build2) ...
update-alternatives: using /usr/bin/telnet.netkit to provide /usr/bin/telnet (telnet) in auto mode
Setting up schroot-common (1.6.8-1ubuntu1.1) ...
Setting up schroot (1.6.8-1ubuntu1.1) ...
Setting up kpartx (0.4.9-3ubuntu7.11) ...
Processing triggers for libc-bin (2.19-0ubuntu6.7) ...
Processing triggers for ureadahead (0.100.0-16) ...
- dpkg -i /tmp/ibm-datapower-common.deb /tmp/ibm-datapower-image.deb
  Selecting previously unselected package ibm-datapower-common.
  (Reading database ... 11714 files and directories currently installed.)
  Preparing to unpack /tmp/ibm-datapower-common.deb ...
  Unpacking ibm-datapower-common (7.5.0.0.274960) ...
  Selecting previously unselected package ibm-datapower-agoradco-image.
  Preparing to unpack /tmp/ibm-datapower-image.deb ...
  Unpacking ibm-datapower-agoradco-image (7.5.0.0.274960) ...
  Setting up ibm-datapower-agoradco-image (7.5.0.0.274960) ...
  Setting up ibm-datapower-common (7.5.0.0.274960) ...
  Processing triggers for ureadahead (0.100.0-16) ...
- sed -i -e /^web-mgmt/,/^exit/s/admin-state.*/admin-state "enabled"/g /opt/ibm/datapower/datapower-external.cfg
- rm /tmp/ibm-datapower-common.deb /tmp/ibm-datapower-image.deb
- /opt/ibm/datapower/datapower-docker-build.sh
- mkdir -p /datapower/config /datapower/local
- echo DataPowerConfigDir=/datapower/config
- echo DataPowerLocalDir=/datapower/local
- echo DataPowerCpuCount=4
- echo DataPowerMemoryLimit=8000
  ---> c415e4c3d13a
  Removing intermediate container 5c3d2ce88efe
  Step 5 : EXPOSE 9090
  ---> Running in c0b9ce7f4781
  ---> 8d57b851db74
  Removing intermediate container c0b9ce7f4781
  Step 6 : CMD /opt/ibm/datapower/datapower-launch
  ---> Running in e9432923bcaf
  ---> d0bca646f75a
  Removing intermediate container e9432923bcaf
  Successfully built d0bca646f75a

**Comment by lubosures** [comment]
The failure reason is reported in the first 3 log lines:
ERR dpControl [pre-start][20] Cannot run losetup --show --find /var/opt/ibm/datapower/datapower.img
ERR dpControl [pre-start][20] losetup: losetup: Could not find any loop device. Maybe this kernel does not know
ERR dpControl [pre-start][20] losetup: about the loop device? (If so, recompile or `modprobe loop'.)

The host MUST have at least TWO free loop devices, otherwise the datapower container is unable to start. Use an appropriate method on your linux host to make sure at least 2 loop devices are available before starting the docker container.

**Comment by ibm-om** [comment]
Ted,
I authored the Quick Start Guide and failed to add the bullet point regarding the need for two unused loop mount devices per instance (with one additional if you want to configure RAID device). We have this in the 'main' documentation but this one slipped through the review process.

We have amended the document and everyone will benefit from your find, so Thank You very much!
Also, please accept my apologies for any wasted time or frustration you experienced.

**Comment by tsikorski** [comment]
Hi,
thanks for the quick reply. I didn't spend a lot of time on this before I submitted this.
So I added some loop devices on the host machine and now the error messages changed:

 docker run -it --privileged  -h datapower datapower /bin/bash

root@datapower:/# /opt/ibm/datapower/datapower-launch
cp: cannot stat '/etc/redhat-release': No such file or directory
Thu Apr 28 2016 18:28:06 ERR dpControl [pre-start][71] Execution of 'cmp -s /etc/redhat-release /tmp/ibm-dp-container-1-71-1461868083/primary/etc/redhat-release || cp -f /etc/redhat-release /tmp/ibm-dp-container-1-71-1461868083/primary/etc/redhat-release' failed: Operation not permitted
cp: cannot stat '//.dockerinit': No such file or directory
Thu Apr 28 2016 18:28:06 ERR dpControl [pre-start][71] Execution of 'cmp -s //.dockerinit /tmp/ibm-dp-container-1-71-1461868083/primary/.dockerinit || cp -f //.dockerinit /tmp/ibm-dp-container-1-71-1461868083/primary/.dockerinit' failed: Operation not permitted
Thu Apr 28 2016 18:28:06 INF dpControl [pre-start][71] Processing /tmp/ibm-dp-container-1-71-1461868083/primary/etc/datapower.conf
Thu Apr 28 2016 18:28:06 INF dpControl [pre-start][71] Standby Control Not Enabled
Thu Apr 28 2016 18:28:06 INF dpControl [pre-start][71] RaidBlockDeviceName is not specified
Thu Apr 28 2016 18:28:08 ERR dpControl [session][71] Cannot create schroot session, rc=1
Thu Apr 28 2016 18:28:08 ERR dpControl [session][71]    schroot: E: 10mount: mount: could not find any free loop device
Thu Apr 28 2016 18:28:08 ERR dpControl [session][71]    schroot: E: var_opt_ibm_datapower_datapower_img-f7a7d864-8134-465e-b3aa-6b285dcfee69: Chroot setup failed: stage=setup-start
Thu Apr 28 2016 18:28:08 ERR dpControl [session][71] Cannot retrieve sessionName

**Comment by lubosures** [comment]
Ted, you can ignore the failed copy operations, they don't look nice but are harmless in your situation. The pre-start step appears to be completed but the the session can't be started for the same reason as before:
ERR dpControl [session][71] schroot: E: 10mount: mount: could not find any free loop device

**Comment by tsikorski** [comment]
Thanks for the reply. I thought that two would not be enough so I added more:
See the output from the running container:

Notice the initial messages regarding loop devices are no longer there these are new messages:

Fri Apr 29 2016 13:09:44 ERR dpControl [session][16] Cannot create schroot session, rc=1
Fri Apr 29 2016 13:09:44 ERR dpControl [session][16]    schroot: E: 10mount: mount: could not find any free loop device
Fri Apr 29 2016 13:09:44 ERR dpControl [session][16]    schroot: E: var_opt_ibm_datapower_datapower_img-d0c04dad-78ef-44c0-ab45-c83ccbac554d: Chroot setup failed: stage=setup-start
Fri Apr 29 2016 13:09:44 ERR dpControl [session][16] Cannot retrieve sessionName
root@datapower:/# ls /dev/loop*
/dev/loop-control  /dev/loop0  /dev/loop1  /dev/loop2  /dev/loop3  /dev/loop8

I guess the question is how many do I need?

**Comment by ibm-om** [comment]
We support Docker Engine 1.8, 1.9 at this time.

**Comment by tsikorski** [comment]
Ah that would explain it.
Any time frame on moving to the at least 10 or 11. Things changed in 10 with capabilities (which I tried adding as well to no avail).

I guess we will have to wait till 1.11 is supported since I am already at version 1.11 and have no desire to fall back to pre 10. 

Ted

**Comment by ibm-om** [comment]
The ease of setting up a test environment may help your investigation of how useful DataPower is, for what you want to do. Production stability is our primary concern for the product, but you should also know that we are having very good response to Docker, which could stimulate the pace of development. Your support and feedback are instrumental in helping that happen best.

**Comment by lubosures** [comment]
Ted,

while 1.11 is not officially tested and supported, there seem to be no problems to start datapower in Docker 1.11 environment.
Can you pls run the following exercise and check if losetup can or cannot associate 2 loop devices with files file1 and file2:

dd if=/dev/zero of=file1 bs=1 seek=$((1024<<20)) count=0
dd if=/dev/zero of=file2 bs=1 seek=$((1024<<20)) count=0
sudo losetup --find --show file1
**/dev/loop10**
sudo losetup --find --show file2
**/dev/loop11**
sudo losetup -d /dev/loop11
sudo losetup -d /dev/loop10
rm file1 file2

**Comment by tsikorski** [comment]
Hi,
I think you are on to something here. It looks like I have some sort of permission issue with the loop devices and the docker container.
The above commands fail.

**Comment by tsikorski** [comment]
Hi,
thanks for the tips. I had the minor number of the loop back device set incorrectly. I created an entry /etc/modprobe.d giving me lots of loopback devices a quick reboot and it appears I am good to go with 1.11.

thanks.

**Comment by hstenzel** [comment]
Excellent, glad to hear all's well.

I'm going to go ahead and close this issue.
