### ISSUE TITLE
After successful start and stop container can not be started again.

### ISSUE THREAD

**Issue by tsikorski** [ibm-datapower/datapower-labs#4]
Hi,
After successfully starting the datapower container on docker 1.11 I decided to stop the container and start it up again. 
I ran the following:

 docker run -d  -h datapower --name=datapower  --privileged -p 9090:9090 datapower
 docker stop datapower
 docker rm -v datapower
This last command resulted in the following error message:

Error response from daemon: Driver devicemapper failed to remove root filesystem 64636c8d9dfc842933d4ad95917d5d0394993c006f8bcc0a2ee5b5a445afad1a: Device is Busy

A restart of the docker service was needed to clear this message.

Then I tried to start the container again and ended up with the following message

systemctl restart docker
[root@testbed2 ~]# docker rm datapower
Error response from daemon: No such container: datapower
[root@testbed2 ~]# docker run -d  -h datapower --name=datapower  --privileged -p 9090:9090 datapower

5a48e3ef22f0b00dcc492980f4c8736b47d821d601ac23325cd438a489e6c376

[root@testbed2 ~]# docker logs 5a48e3ef22f0b00dcc492980f4c8736b47d821d601ac23325cd438a489e6c376
Sat Apr 30 2016 03:52:50 ERR dpControl [pre-start][1] Cannot unlock LUKS partition 'var_opt_ibm_datapower_datapower_img': File exists (error 17)
Sat Apr 30 2016 03:52:50 ERR dpControl [pre-start][1] Cannot open lockfile '/var/opt/ibm/datapower/datapower.img.lck': No such file or directory

Which probably revolves around something not being freed as a result of running in privileged mode. 

At this point a restart of the operating system was needed to be able to start this container again. 

Just as an FYI I had 8 free loop devices defined to the system. 

If datapower was the only container running on this system a OS restart is not such a big thing however that is not an acceptable way of running long term.

This might be a docker issue however given that this container requires elevated privileges I suspect a combination a docker bug and some cleanup error might be to blame.

A friendly suggestion.

Rather than running a container within a container which is what you seem to be doing here. You might want to think of a way of packaging a busybox container and running your code natively.

You seem to start ubuntu or redhat as the driving OS for your container then you schroot into busybox (at least on the surface you seem to be doing that).

I really don't think this methodology is sustainable long term given the way docker is going.

Just a thought.

Ted

**Comment by lubosures** [comment]
Ted,
datapower cannot stop within the default 10 seconds timeout allowed by the docker daemon. You need to stop the docker instance with an explicitly specified timeout of approximately 60 seconds. 
Please use **docker stop -t 60 <containerid>** instead of the default stop command.

**Comment by tsikorski** [comment]
Hi,
Thanks the timeout has fixed the problem.
