### ISSUE TITLE
Docker toolbox windows environment Datapower starts but never listens on port 9090

### ISSUE THREAD

**Issue by tsikorski** [ibm-datapower/datapower-labs#5]
After building the debian image in the windows toolbox environment I successfully started datapower however when I exec into the system I see that the environment has started but a listen for port 9090 doesn't ever happen.

Here are the log messages:

$ docker logs datapower
cp: cannot create regular file '/tmp/ibm-dp-container-1-1-1462374806/primary/drouter/internalconfig/datapower-external.cfg': Read-only file system
Wed May 04 2016 15:13:27 ERR dpControl [pre-start][1] Execution of 'cmp -s /var/opt/ibm/datapower/datapower-external.cfg /tmp/ibm-dp-container-1-1-1462374806/primary/drouter/internalconfig/datapower-external.cfg || cp -f /var/opt/ibm/datapower/datapower-external.cfg /tmp/ibm-dp-container-1-1-1462374806/primary/drouter/internalconfig/datapower-external.cfg' failed: Operation not permitted
cp: cannot create regular file '/tmp/ibm-dp-container-1-1-1462374806/primary/etc/hosts.host': Read-only file system
Wed May 04 2016 15:13:27 ERR dpControl [pre-start][1] Execution of 'cmp -s /etc/hosts /tmp/ibm-dp-container-1-1-1462374806/primary/etc/hosts.host || cp -f /etc/hosts /tmp/ibm-dp-container-1-1-1462374806/primary/etc/hosts.host' failed: Operation not permitted
cp: cannot create regular file '/tmp/ibm-dp-container-1-1-1462374806/primary/etc/resolv.conf.host': Read-only file system
Wed May 04 2016 15:13:27 ERR dpControl [pre-start][1] Execution of 'cmp -s /etc/resolv.conf /tmp/ibm-dp-container-1-1-1462374806/primary/etc/resolv.conf.host || cp -f /etc/resolv.conf /tmp/ibm-dp-container-1-1-1462374806/primary/etc/resolv.conf.host' failed: Operation not permitted
cp: cannot create regular file '/tmp/ibm-dp-container-1-1-1462374806/primary/etc/os-release': Read-only file system
Wed May 04 2016 15:13:27 ERR dpControl [pre-start][1] Execution of 'cmp -s /etc/os-release /tmp/ibm-dp-container-1-1-1462374806/primary/etc/os-release || cp -f /etc/os-release /tmp/ibm-dp-container-1-1-1462374806/primary/etc/os-release' failed: Operation not permitted
cp: cannot stat '/etc/redhat-release': No such file or directory
Wed May 04 2016 15:13:27 ERR dpControl [pre-start][1] Execution of 'cmp -s /etc/redhat-release /tmp/ibm-dp-container-1-1-1462374806/primary/etc/redhat-release || cp -f /etc/redhat-release /tmp/ibm-dp-container-1-1-1462374806/primary/etc/redhat-release' failed: Operation not permitted
cp: cannot create regular file '/tmp/ibm-dp-container-1-1-1462374806/primary/.dockerenv': Read-only file system
Wed May 04 2016 15:13:27 ERR dpControl [pre-start][1] Execution of 'cmp -s //.dockerenv /tmp/ibm-dp-container-1-1-1462374806/primary/.dockerenv || cp -f //.dockerenv /tmp/ibm-dp-container-1-1-1462374806/primary/.dockerenv' failed: Operation not permitted
cp: cannot stat '//.dockerinit': No such file or directory
Wed May 04 2016 15:13:27 ERR dpControl [pre-start][1] Execution of 'cmp -s //.dockerinit /tmp/ibm-dp-container-1-1-1462374806/primary/.dockerinit || cp -f //.dockerinit /tmp/ibm-dp-container-1-1-1462374806/primary/.dockerinit' failed: Operation not permitted
cp: cannot create regular file '/tmp/ibm-dp-container-1-1-1462374806/primary/root/product_uuid': Read-only file system
Wed May 04 2016 15:13:27 ERR dpControl [pre-start][1] Execution of 'cmp -s /sys/devices/virtual/dmi/id/product_uuid /tmp/ibm-dp-container-1-1-1462374806/primary/root/product_uuid || cp -f /sys/devices/virtual/dmi/id/product_uuid /tmp/ibm-dp-container-1-1-1462374806/primary/root/product_uuid' failed: Operation not permitted
cp: cannot create regular file '/tmp/ibm-dp-container-1-1-1462374806/primary/root/uuid.rand': Read-only file system
Wed May 04 2016 15:13:27 ERR dpControl [pre-start][1] Execution of 'cmp -s /proc/sys/kernel/random/uuid /tmp/ibm-dp-container-1-1-1462374806/primary/root/uuid.rand || cp -f /proc/sys/kernel/random/uuid /tmp/ibm-dp-container-1-1-1462374806/primary/root/uuid.rand' failed: Operation not permitted
cp: cannot create regular file '/tmp/ibm-dp-container-1-1-1462374806/primary/etc/datapower.conf': Read-only file system
Wed May 04 2016 15:13:27 ERR dpControl [pre-start][1] Execution of 'cmp -s /var/opt/ibm/datapower/datapower.conf /tmp/ibm-dp-container-1-1-1462374806/primary/etc/datapower.conf || cp -f /var/opt/ibm/datapower/datapower.conf /tmp/ibm-dp-container-1-1-1462374806/primary/etc/datapower.conf' failed: Operation not permitted
Wed May 04 2016 15:13:27 INF dpControl [pre-start][1] Processing /tmp/ibm-dp-container-1-1-1462374806/primary/etc/datapower.conf
Wed May 04 2016 15:13:27 INF dpControl [pre-start][1] Standby Control Not Enabled
Wed May 04 2016 15:13:27 INF dpControl [pre-start][1] RaidBlockDeviceName is not specified
Wed May 04 2016 15:13:29 INF dpControl [session][1] Starting DataPower service ...

$ docker exec -it datapower /bin/bash
root@datapower:/# netstat -tan
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:2200            0.0.0.0:\*               LISTEN

> ```
>  0:00 ps ax
> ```
> 
> root@datapower:/# ps axww
>  PID TTY      STAT   TIME COMMAND
>   1 ?        SLs    0:01 /opt/ibm/datapower/datapower-launch
>   74 ?        S      0:00 sh -c schroot --run-session --chroot var_opt_ibm_datapower_datapower_img-1af0d4d3-f7d2-4776-806b-67e698eb9d63 -- /bin/supervisor -m /dev/mapper/var_opt_ibm_datapower_datapower_img
>   75 ?        S      0:00 schroot --run-session --chroot var_opt_ibm_datapower_datapower_img-1af0d4d3-f7d2-4776-806b-67e698eb9d63 -- /bin/supervisor -m /dev/mapper/var_opt_ibm_datapower_datapower_img
>   76 ?        S      0:00 [init]          -m /dev/mapper/var_opt_ibm_datapower_datapower_img
>  77 ?        Ssl    0:00 [main]          -m /dev/mapper/var_opt_ibm_datapower_datapower_img
> 11259 ?        Ss     0:00 /bin/bash

Running the latest docker toolbox 1.11.1

**Comment by hstenzel** [comment]
Can you tell us which makefile target you're using?

**Comment by hstenzel** [comment]
Wouldn't we also need to address password maps at the same time? Keys are expected to be encrypted and unlocked with password maps, how much good does it do to have the key files themselves be available but not to have the password map?

**Comment by tsikorski** [comment]
Hi
I am not using a makefile but instead am using the following Dockerfile:

$ cat Dockerfile
FROM ubuntu:trusty
COPY ibm-datapower-common.deb ibm-datapower-image.deb /tmp/
ENV DEBIAN_FRONTEND noninteractive
RUN set -x \
&& apt-get update \
&& apt-get -y upgrade \
&& apt-get -y install \
kpartx \
schroot \
telnet \
&& dpkg -i /tmp/ibm-datapower-common.deb /tmp/ibm-datapower-image.deb \
&& sed -i \
-e '/^web-mgmt/,/^exit/s/admin-state.*/admin-state "enabled"/g' \
/opt/ibm/datapower/datapower-external.cfg \
&& rm /tmp/ibm-datapower-common.deb /tmp/ibm-datapower-image.deb \
&& /opt/ibm/datapower/datapower-docker-build.sh \
&& mkdir -p /datapower/config /datapower/local \
&& echo "DataPowerConfigDir=/datapower/config" >> /opt/ibm/datapower/datapower.conf \
&& echo "DataPowerLocalDir=/datapower/local" >> /opt/ibm/datapower/datapower.conf \
&& echo "DataPowerCpuCount=2" >> /opt/ibm/datapower/datapower.conf \
&& echo "DataPowerMemoryLimit=4000" >> /opt/ibm/datapower/datapower.conf
EXPOSE 9090
CMD ["/opt/ibm/datapower/datapower-launch"]

**Comment by tsikorski** [comment]
Hi,
I figured it out.
I was starting the service from the toolbox quickstart shell. What I should have done is the following:

after starting the  quickstart shell

> docker-machine ssh
> cd to the directory that contains the Dockerfile and .deb files
> build the image (be patient)
> docker run -d ....

All ports appear to start and I am able to access the web gui.

I think that issuing the docker run command with the privileged flag while running in a windows environment doesn't make sense. 

Thanks for your time.

Ted
