### ISSUE TITLE
schroot rpm does not use EPEL

### ISSUE THREAD

**Issue by hstenzel** [ibm-datapower/datapower-labs#6]
In several places, the schroot rpm is pulled directly from a url. It should not work this way, we should first install EPEL then let "yum install" pull in the schroot dependency.

**Comment by hstenzel** [comment]
This problem exists in rpm2img and customer-optimized

**Comment by jpmatamo** [comment]
fixed for rpm2img, need to fix for customer-optimized

**Comment by jpmatamo** [comment]
Fixed. Closing
