### ISSUE TITLE
Running datapower on OpenShift

### ISSUE THREAD

**Issue by sburke67** [ibm-datapower/datapower-labs#8]
Hi, was just wondering if anyone had managed to get datapower running on OpenShift?

I can run my image via docker on my openshift nodes:
docker run --privileged -p 9290:9090 ibm-datapower-licensed
Fri Aug 05 2016 10:28:55 INF dpControl [pre-start][1] Processing /tmp/ibm-dp-container-1-1-1470407332/primary/etc/datapower.conf
Fri Aug 05 2016 10:28:55 INF dpControl [pre-start][1] Standby Control Not Enabled
Fri Aug 05 2016 10:28:55 INF dpControl [pre-start][1] RaidBlockDeviceName is not specified
Fri Aug 05 2016 10:28:56 INF dpControl [session][1] Starting DataPower service ...
and I can connect to the WEBUI via localhost:9290

 but get the following in the OpenShift logs when I try and launch it that way:

mount: permission denied
Fri Aug 05 2016 10:26:37 ERR dpControl [pre-start][1] Execution of 'mount --make-rprivate /' failed: Broken pipe
Fri Aug 05 2016 10:26:38 ERR dpControl [pre-start][1] Cannot run losetup --show --find /var/opt/ibm/datapower/ibm-datapower-licensed-1-7b3sh.datapower.img
Fri Aug 05 2016 10:26:38 ERR dpControl [pre-start][1]    losetup: losetup: /var/opt/ibm/datapower/ibm-datapower-licensed-1-7b3sh.datapower.img: failed to set up loop device: No such file or directory
Fri Aug 05 2016 10:26:38 ERR dpControl [post-stop][1] Cannot open lockfile '/var/opt/ibm/datapower/ibm-datapower-licensed-1-7b3sh.datapower.img.lck': No such file or directory
/dev/mapper/control: mknod failed: Operation not permitted
Failure to communicate with kernel device-mapper driver.
Check that device-mapper is available in the kernel.
Fri Aug 05 2016 10:26:38 ERR dpControl [post-stop][1] Cannot close LUKS partition 'var_opt_ibm_datapower_ibm-datapower-licensed-1-7b3sh_datapower_img': No such device (error 19)
Fri Aug 05 2016 10:26:38 ERR dpControl [post-stop][1] Cannot open lockfile '/var/opt/ibm/datapower/ibm-datapower-licensed-1-7b3sh.datapower.img.lck': No such file or directory
Fri Aug 05 2016 10:26:39 ERR dpControl [post-stop][1] Cannot open lockfile '/var/opt/ibm/datapower/ibm-datapower-licensed-1-7b3sh.datapower.img.lck': No such file or directory
Fri Aug 05 2016 10:26:39 ERR dpControl [post-stop][1] Cannot open lockfile '/var/opt/ibm/datapower/ibm-datapower-licensed-1-7b3sh.datapower.img.lck': No such file or directory

Any thoughts?

Cheers

Sean

**Comment by hstenzel** [comment]
Sean,

It looks like DataPower's reliance on `--privileged` combined with OpenShift's permission model  is the source of the problems.  This is an issue we are aware of.

We just released a beta version that does not have that requirement. If you're game, I'd suggest trying that:

https://hub.docker.com/r/ibmcom/datapower/

I think you'll get quite a bit farther with the beta -- it does not require privileged.

 --Harley

**Comment by sburke67** [comment]
Hi Harley,

thanks for the info, will give it a try asap

Cheers

Sean

**Comment by sburke67** [comment]
Hi Harley, FYI, this spins up ok in OpenShift

Reading the info on that webpage you sent, I was trying to get the web-mgmt port to work, but for some reason it doesn't launch

I'm running ... docker run -it -p 9290:9090 -e DATAPOWER_ACCEPT_LICENSE=true datapower

So this should expose 9290 on the localhost my docker image is running on, but it doesn't work (9090 is already in use by openshift)

Is there any pre-reqs I need to do?

When I was working from the factory to the licenced build, this launched ok in Docker  (I changed the pw, launched the webui, accepted licence etc)

Cheers

Sean

**Comment by jefurbee** [comment]
Hi Sean,
Did you log into DataPower and enable the web-gui? Here are the CLI commands:
top;co;web-mgmt;admin enabled;exit;write mem

I ran this command......docker run -it -e DATAPOWER_INTERACTIVE=true -e DATAPOWER_ACCEPT_LICENSE=true -p 9290:9090 --name datapowertest dockerlight:latest /root/drouter

and then enabled the webgui and was able to log in using the url https://dpipaddress:9092 using a Chrome browser.

Thanks,
joe

**Comment by sburke67** [comment]
hi Joe,

thanks for that mate, it is working now :-)

Cheers

Sean

**Comment by jpmatamo** [comment]
great to hear, closing this issue.
